name: Test game source

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-source:
    runs-on: ubuntu-latest

    steps:
      - name: Download wiki data repository
        uses: actions/checkout@v7

      - name: Download game repository
        uses: actions/checkout@v7
        with:
          repository: MetalSage/space-stories-cm14
          ref: master
          path: game-source
          sparse-checkout: README.md
          sparse-checkout-cone-mode: false

      - name: Create source information
        run: |
          mkdir -p data

          GAME_COMMIT=$(git -C game-source rev-parse HEAD)

          cat > data/source.json << EOF
          {
            "status": "ok",
            "repository": "MetalSage/space-stories-cm14",
            "branch": "master",
            "commit": "$GAME_COMMIT",
            "generatedAt": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          }
          EOF

      - name: Save source information
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/source.json

          if git diff --cached --quiet; then
            echo "Nothing changed"
          else
            git commit -m "Test game repository connection"
            git push
          fi
